# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CheckOut 
        uses: actions/checkout@master
      
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 这里使用了别人写好的action
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vuepress/dist # The folder the action should deploy.
        env:
          # GITHUBACTION_TOKEN就是上文创建的Github秘钥的名字
          ACCESS_TOKEN: ${{ secrets.GITHUBACTION_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          # BUILD_SCRIPT: npm install && npm run docs:build
